/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample;

import Middleware.*;
import org.apache.thrift.TException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        try {
            Client client = new Client("localhost", 9090);

            List<String> nameList = new ArrayList<>();
            nameList.add("Đạt");
            nameList.add("Quý");
            nameList.add("Tính");

            List<String> genderList = new ArrayList<>();
            genderList.add("Male");
            genderList.add("Female");

            Random rand = new Random();
            while (true) {
                int id = rand.nextInt(1000000);
                String name = nameList.get(rand.nextInt(3));
                String gender = genderList.get(rand.nextInt(2));
                int age = rand.nextInt(65);

                Person person = new Person();
                person.setId(Integer.toString(id));
                person.setName(name);
                person.setGender(gender);
                person.setAge(Integer.toString(age));

                boolean putSuccess = client.putToDatabase(person);
                person.clear();
                System.out.println("Put success: " + putSuccess);

                person = client.getFromDatabase(Integer.toString(id));
                System.out.println("Person is got: " + person);

                int nextPrimeNumber = client.nextPrimeNumber(id);
                System.out.println("Next prime of " + id + " is: " + nextPrimeNumber);

                Thread.sleep(300);
            }

        } catch (TException | InterruptedException e) {
            e.printStackTrace();
        }

    }
}